project:
  type: website
  output-dir: docs
  #pre-render: https://platform.twitter.com/widget.js
execute:
  freeze: auto
website:
  #margin-header: images/logo-ifb-mono-metabohub_2.1_SD_150px.png
  #announcement:
  #  icon: info-cricle
  #  dismissable: true
  #  content: "**Important** - this website is under construction !"
  #  type: warning
  #  position: below-navbar
  title: "Workflow4Metabolomics"
  #site-url: https://workflow4metabolomics.github.io/
  favicon: images/w4m.png
  twitter-card: true
  page-footer:
    right: "This page is built with ❤️"
    left: "Contact us: workflow4metabolomics@proton.me"


  # theme:
  #   light: flatly
  #   dark: darkly
  navbar:
    logo: images/w4m.png
    href: https://workflow4metabolomics.org/
    left:
      - text: "Home"
        href: index.qmd
        icon: "house"
      - text: "Galaxy W4M"
        icon: "boxes"
        menu:
          - text: "Introduction"
            href: galaxyW4M.qmd
            icon: "info-circle"
          - text: "Guides for Users"
            href: tooluser.qmd
            icon: "code"
          - text: "Guides for Developpers"
            href: tooldev.qmd
            icon: "code"
          - text: "Guides for Administrators"
            href: tooladmin.qmd
            icon: "code"
          - text: "How to get help"
            href: get_help.qmd
            icon: "person-fill-up"
          - text: "How to contribute"
            href: contribute.qmd
            icon: "person-fill-up"
      - text: "Tools"
        icon: "tools"
        menu:
          - text: "Tool 1"
            href: tool1.qmd
          - text: "Tool 2"
            href: tool2.qmd
      - text: "News & Events"
        icon: "calendar-week"
        href: news.qmd
      - text: "W4M Team"
        icon: "people"
        href: listing_team.qmd
      - text: "About"
        href: about.qmd


    #background: success
    #foreground: danger
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/company/workflow4metabolomics/
      - icon: github
        menu:
        - text: Source Code
          url: https://github.com/workflow4metabolomics/workflow4metabolomics
        - text: Report a Bug
          url: https://github.com/workflow4metabolomics/workflow4metabolomics/issues
        - text: Contribute
          url: https://github.com/workflow4metabolomics/workflow4metabolomics//Workflow4Metabolomics%20Galaxy%20Documentation#readme
    pinned: true
    sidebar:
      style: "docked"
      search: FALSE
      # contents:
      #   - section: "Home"
      #   contents:
      #     _ index.qmd
      #     - home.qmd
      #   - section: "Tools"
      #   contents:
      #     - about.qmd
      #     - tool1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual

